# Generated by Django 5.2.17 on 2026-08-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_document_document_type_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path within the Supabase Storage bucket — not a URL. The bucket is private, so viewing a document means minting a fresh signed URL on demand (see admissions/storage.py) rather than storing one, since a signed URL created before the file exists would 404, and one stored long-term would eventually expire silently.', max_length=500),
        ),
    ]
