# Generated by Django 5.2.17 on 2026-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_remove_document_file_url_document_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, help_text="Format APP-YYYY-NNNN. Assigned once, the first time this row's stage reaches 'application' or later (whether created there directly or advanced from an inquiry) — never reassigned as it moves further through the pipeline.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='inquiry_reference',
            field=models.CharField(blank=True, help_text="Format INQ-YYYY-NNNN. Assigned once, only if this row was created at stage='inquiry' — never backfilled for rows that skip straight to 'application'.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text="Permanent ID, format YYPPNNNN (year + classification + roll number). Assigned once, the first time any of this student's Applications reaches stage='enrolled' — see Application.save() and STUDENT_ID_CLASSIFICATION.", max_length=20, null=True, unique=True),
        ),
    ]
