# Generated by Django 5.2.17 on 2026-08-26 04:57

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_application_stage_capacity_decision_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'campuses',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_signature_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='media_consent_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_interest_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='wants_scholarship_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_location',
            field=models.CharField(blank=True, default='', help_text="Address/location of current_school — distinct from current_school itself, which is the school's name", max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='town_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('proof_of_vaccination', 'Proof of Vaccination'), ('financial_clearance', 'Proof of Financial Clearance from Previous School'), ('previous_report', 'Report Card / Transcript from Previous School'), ('application_fee_proof', 'Proof of Application Fee Payment'), ('proof_of_funds', 'Proof of Funds'), ('passport_photo', 'Passport Photograph'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=admissions.models._generate_draft_token, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, default='', help_text='Captured once the guardian email step is filled in', max_length=254)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=admissions.models._default_draft_expiry)),
                ('submitted_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='admissions.application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='capacity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.campus'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Leave blank if this grade's capacity isn't campus-specific.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capacities', to='admissions.campus'),
        ),
        migrations.AlterUniqueTogether(
            name='capacity',
            unique_together={('academic_year', 'year_group', 'campus')},
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(help_text='Free text — e.g. aunt, family friend, grandmother', max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_learning_or_physical_needs', models.BooleanField(default=False)),
                ('learning_or_physical_needs_details', models.TextField(blank=True, default='')),
                ('has_medical_conditions', models.BooleanField(default=False)),
                ('medical_conditions_details', models.TextField(blank=True, default='')),
                ('has_allergies_or_dietary_requirements', models.BooleanField(default=False)),
                ('allergies_dietary_details', models.TextField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='admissions.application')),
            ],
            options={
                'permissions': [('can_view_health_info', 'Can view health/wellbeing info')],
            },
        ),
    ]
