# Generated by Django 5.2.17 on 2026-08-27 05:33

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_seed_campuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='bulk_email_unsubscribe_token',
            field=models.CharField(blank=True, default=admissions.models._generate_unsubscribe_token, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='bulk_email_unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label — not shown to recipients', max_length=255)),
                ('subject', models.CharField(help_text='Supports {{placeholders}} — see bulk_email.py', max_length=255)),
                ('body', models.TextField(help_text='Plain text. Supports {{guardian_first_name}}, {{guardian_full_name}}, {{student_names}}, {{unsubscribe_link}} — {{unsubscribe_link}} is required.')),
                ('filter_stage', models.CharField(blank=True, choices=[('inquiry', 'Inquiry'), ('application', 'Application'), ('document_review', 'Document Review'), ('offer', 'Offer'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('offer_declined', 'Offer Declined')], default='', help_text='Blank = no filter (every stage)', max_length=20)),
                ('filter_academic_year', models.CharField(blank=True, default='', help_text='Blank = no filter', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('filter_campus', models.ForeignKey(blank=True, help_text='Blank = no filter', null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.campus')),
            ],
            options={
                'permissions': [('can_send_bulk_email', 'Can send bulk/marketing email campaigns')],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_unsubscribed', 'Skipped (unsubscribed)')], default='pending', max_length=25)),
                ('resend_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='admissions.emailcampaign')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_email_recipient_records', to='admissions.guardian')),
            ],
            options={
                'unique_together': {('campaign', 'guardian')},
            },
        ),
    ]
