# Generated by Django 5.2.17 on 2026-08-27 05:33

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_backfill_guardian_unsubscribe_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='bulk_email_unsubscribe_token',
            field=models.CharField(default=admissions.models._generate_unsubscribe_token, max_length=64, unique=True),
        ),
    ]
