# Generated by Django 5.2.17 on 2026-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_guardian_unsubscribe_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, help_text='Recipients skipped before ever reaching Resend — malformed or placeholder addresses.'),
        ),
        migrations.AlterField(
            model_name='emailcampaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_unsubscribed', 'Skipped (unsubscribed)'), ('skipped_invalid', 'Skipped (invalid address)')], default='pending', max_length=25),
        ),
    ]
