# Generated by Django 5.2.17 on 2026-09-01 20:11

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_phase6_skipped_invalid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('grade_interest', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(choices=[('quick_interest_widget', 'Quick-interest widget'), ('pdf_gate_admissions_overview', 'PDF gate — Admissions Overview & Fees')], max_length=40)),
                ('consent_to_marketing', models.BooleanField(default=False, help_text='Genuine opt-in only — defaults False even if a form omits the field.')),
                ('bulk_email_unsubscribe_token', models.CharField(default=admissions.models._generate_unsubscribe_token, max_length=64, unique=True)),
                ('bulk_email_unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='emailcampaignrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='audience',
            field=models.CharField(choices=[('guardians', 'Guardians'), ('leads', 'Leads'), ('both', 'Guardians + Leads')], default='guardians', help_text='Who this campaign is sent to. Leads are always further restricted to consent_to_marketing=True and not unsubscribed.', max_length=10),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='filter_lead_source',
            field=models.CharField(blank=True, choices=[('quick_interest_widget', 'Quick-interest widget'), ('pdf_gate_admissions_overview', 'PDF gate — Admissions Overview & Fees')], default='', help_text='Blank = all lead sources. Only applies when Audience includes Leads.', max_length=40),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='body',
            field=models.TextField(help_text='Plain text. Supports {{recipient_first_name}}, {{recipient_full_name}} (work for both Guardians and Leads), {{guardian_first_name}}, {{guardian_full_name}} (back-compat aliases), {{student_names}}, {{unsubscribe_link}} — {{unsubscribe_link}} is required.'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='filter_academic_year',
            field=models.CharField(blank=True, default='', help_text='Blank = no filter. Only applies to the Guardian audience.', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='filter_campus',
            field=models.ForeignKey(blank=True, help_text='Blank = no filter. Only applies to the Guardian audience.', null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.campus'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='filter_stage',
            field=models.CharField(blank=True, choices=[('inquiry', 'Inquiry'), ('application', 'Application'), ('document_review', 'Document Review'), ('offer', 'Offer'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('offer_declined', 'Offer Declined')], default='', help_text='Blank = no filter (every stage). Only applies to the Guardian audience.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaignrecipient',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_email_recipient_records', to='admissions.guardian'),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_email_recipient_records', to='admissions.lead'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaignrecipient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guardian__isnull', False), ('lead__isnull', True)), models.Q(('guardian__isnull', True), ('lead__isnull', False)), _connector='OR'), name='emailcampaignrecipient_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaignrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('guardian__isnull', False)), fields=('campaign', 'guardian'), name='uniq_campaign_guardian'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaignrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False)), fields=('campaign', 'lead'), name='uniq_campaign_lead'),
        ),
    ]
