# Generated by Django 5.2.17 on 2026-09-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_lead_and_campaign_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inquiry_parent', 'Inquiry — parent confirmation'), ('inquiry_staff', 'Inquiry — staff alert'), ('application_parent', 'Application — parent confirmation'), ('application_staff', 'Application — staff alert'), ('draft_resume', 'Application draft — resume link')], max_length=32)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Filenames, resolved against ADMISSIONS_ATTACHMENTS_DIR')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactional_emails', to='admissions.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
