# Generated by Django 5.2.17 on 2026-09-04 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_administration_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_band', models.CharField(blank=True, choices=[('preschool', 'Preschool coordinator (Pre Nursery – Kindergarten 2)'), ('primary', 'Primary coordinator (Grade 1 – 6)'), ('jhs', 'JHS coordinator (Grade 7 – 9)')], default='', help_text="Scopes this user's admin view to one grade band. Leave blank for unscoped staff (Administration members and superusers ignore this field).", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
