# Generated by Django 5.2.17 on 2026-09-26 04:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0019_coordinator_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Matches the ERP's own constraint on account codes.", max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{3,6}$', 'Account code must be 3-6 digits.')])),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expenses', 'Expenses')], max_length=20)),
                ('subtype', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="Null for system-seeded chart-of-accounts rows (the real chart-of-accounts seed migration has no real user to attribute them to) — mirrors the ERP's own resolution of the identical problem in its 20260819090000 migration. Set for any account created for real afterward.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Manual display ordering within a campus.')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='admissions.campus')),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['campus', 'position', 'name'],
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text="The expense's own accounting date — also what numbers its id.")),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_path', models.CharField(blank=True, help_text='Path within a Supabase Storage bucket — not a URL. Same convention as every other file reference in this project (see modules.admissions.models.Document.file_path, modules.hr.models.EmployeeGeneratedDocument.storage_path).', max_length=500)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='admissions.campus')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(help_text="The entry's own accounting date — also what numbers its id.")),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='admissions.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('reverses_entry', models.ForeignKey(blank=True, help_text='Set on a reversal entry, pointing at the original entry it reverses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='finance.journalentry')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Manual display ordering within an entry.')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'ordering': ['entry', 'position'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journalline_debit_gte_0'), models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journalline_credit_gte_0'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journalline_not_both_positive'), models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _negated=True), name='journalline_not_both_zero')],
            },
        ),
    ]
