# Generated by Django 5.2.17 on 2026-09-26 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'permissions': [('can_manage_accounts', 'Can create and edit chart-of-accounts rows')]},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-recorded_at'], 'permissions': [('can_record_expenses', 'Can record operating expenses')]},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='expense',
            field=models.OneToOneField(blank=True, help_text="Set only for entries auto-posted by post_expense() — null for payroll and any other kind of entry. See this model's own docstring.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry', to='finance.expense'),
        ),
        migrations.CreateModel(
            name='ExpenseCategoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_category_mappings', to='finance.account')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_mapping', to='finance.expensecategory')),
            ],
        ),
    ]
