# Generated by Django 5.2.17 on 2026-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_expand_inquiry_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='academic_year',
            field=models.CharField(help_text='e.g. 2026', max_length=50),
        ),
    ]
