# Generated by Django 5.2.17 on 2026-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_application_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('proof_of_vaccination', 'Proof of Vaccination'), ('financial_clearance', 'Proof of Financial Clearance from Previous School'), ('previous_report', 'Report Card / Transcript from Previous School'), ('proof_of_funds', 'Proof of Funds'), ('passport_photo', 'Passport Photograph'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('required', 'Required'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='required', max_length=20),
        ),
    ]
