# Generated by Django 5.2.17 on 2026-08-26 04:58

from django.db import migrations


def seed_campuses(apps, schema_editor):
    Campus = apps.get_model('admissions', 'Campus')
    Campus.objects.get_or_create(name='Main')
    Campus.objects.get_or_create(name='Annex')


def remove_campuses(apps, schema_editor):
    Campus = apps.get_model('admissions', 'Campus')
    Campus.objects.filter(name__in=['Main', 'Annex']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_campus_application_declaration_agreed_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_campuses, remove_campuses),
    ]
