# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('taxable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(help_text="The ERP's own staff ID — kept as the stable external reference across systems.", max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Display/reference only — see the model docstring. Payroll uses EmployeePayConfig.', max_digits=12)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssnit_employee_pct', models.DecimalField(decimal_places=4, help_text="SSNIT Tier 1 — the employee's share, e.g. 0.0050 for 0.5%. Deducted from net pay.", max_digits=5)),
                ('ssnit_employer_pct', models.DecimalField(decimal_places=4, help_text='SSNIT Tier 1 — employer-only, e.g. 0.1300 for 13%. Never touches net pay.', max_digits=5)),
                ('tier2_employee_pct', models.DecimalField(decimal_places=4, help_text='Tier 2 (private trustee) — 100% employee-funded, e.g. 0.0500 for 5%. Deducted from net pay. There is no employer Tier 2 contribution.', max_digits=5)),
                ('effective_from', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pays_ssnit', models.BooleanField(default=True)),
                ('pays_tier2', models.BooleanField(default=True)),
                ('pays_paye', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Blank = current, open-ended.', null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_configs', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PAYEBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_order', models.PositiveSmallIntegerField()),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = unbounded (the top band).', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Decimal fraction, e.g. 0.0500 for 5% — not a whole-number percentage.', max_digits=5)),
                ('effective_from', models.DateField()),
            ],
            options={
                'ordering': ['-effective_from', 'band_order'],
                'unique_together': {('effective_from', 'band_order')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'branch'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ssnit', models.DecimalField(decimal_places=2, default=0, help_text="The employee's 0.5% SSNIT Tier 1 share — deducted from net pay.", max_digits=12)),
                ('tier2', models.DecimalField(decimal_places=2, default=0, help_text="The employee's 5% Tier 2 share (100% employee-funded) — deducted from net pay.", max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ssnit_employer', models.DecimalField(decimal_places=2, default=0, help_text='Employer-side Tier 1 SSNIT cost (13%). Not a deduction from the employee — excluded from total_deductions/net_pay, tracked here purely as an employer cost record. There is no employer-side Tier 2 field — Tier 2 has no employer contribution.', max_digits=12)),
                ('fines', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iou', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['-payroll_run__year', '-payroll_run__month', 'employee'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
