# Generated by Django 5.2.17 on 2026-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_seed_statutory_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-year', '-month', 'branch'], 'permissions': [('can_process_payroll', 'Can create payroll runs, generate payslips, and submit for review'), ('can_approve_payroll', 'Can approve, post, and reject payroll runs')]},
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Required when rejecting a run back to Draft from Ready for Review — see PayrollRunRejectView. Not cleared automatically on the next submit, so a reviewer can still see what was fixed; overwritten by the next rejection, if any.'),
        ),
    ]
