# Generated by Django 5.2.17 on 2026-09-24 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_payroll_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, help_text='Also used to compute probation_duration_months for a Probation Letter, alongside probation_end_date — see documents.build_merge_data().', null=True),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Appointment Letter', 'Appointment Letter'), ('Probation Letter', 'Probation Letter'), ('Contract-Teaching', 'Contract-Teaching'), ('Contract-Non-Teaching', 'Contract-Non-Teaching')], max_length=30, unique=True)),
                ('html_body', models.TextField(blank=True, help_text='{{field}} placeholders only — see documents.build_merge_data() for the exact field list per document kind. Blank means this kind cannot be generated yet.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('Appointment Letter', 'Appointment Letter'), ('Probation Letter', 'Probation Letter'), ('Contract-Teaching', 'Contract-Teaching'), ('Contract-Non-Teaching', 'Contract-Non-Teaching')], max_length=30)),
                ('version', models.PositiveIntegerField(help_text='1-based, per (employee, document_kind).')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Superseded', 'Superseded')], default='Draft', max_length=10)),
                ('storage_path', models.CharField(help_text="Path within the HR_DOCUMENT_STORAGE_BUCKET Supabase Storage bucket — not a URL. The bucket is private, so viewing a document means minting a fresh signed URL on demand (modules/hr/storage.py's create_read_url()) rather than storing one, since a signed URL created before the file exists would 404, and one stored long-term would eventually expire silently.", max_length=500)),
                ('merge_data', models.JSONField(help_text="A frozen snapshot of every field substituted into this specific PDF at generation time — kept even if the employee's own record changes later, so this document's history stays an accurate record of what was actually issued.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_signature_name', models.CharField(blank=True, help_text='HR-recorded, not self-service signing — see documents.record_acceptance().', max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_documents_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='hr.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'document_kind', '-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Issued')), fields=('employee', 'document_kind'), name='one_issued_document_per_employee_kind')],
            },
        ),
    ]
