# Generated by Django 5.2.17 on 2026-09-24 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_seed_contract_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeegenerateddocument',
            constraint=models.UniqueConstraint(fields=('employee', 'document_kind', 'version'), name='unique_document_version_per_employee_kind'),
        ),
    ]
