# Generated by Django 5.2.17 on 2026-09-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_coordinator_groups'),
        ('hr', '0007_employeegenerateddocument_unique_document_version_per_employee_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='admissions.campus'),
        ),
    ]
